# Generated by Django 4.0.1 on 2022-01-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
